include:
  - ./proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: task2_python_web
    container_name: task2-web
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_TABLE=example
      - DB_USER=${MYSQL_USER}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5
  db:
    image: mysql:8
    container_name: task2-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.20.0.10